language: go
go:
  - 1.4
sudo: true
addons:
   apt:
     packages:
      - sshfs
before_install:
  - sudo usermod -a -G fuse $USER
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -P ""
  - touch ~/.ssh/authorized_keys
  - touch ~/.ssh/known_hosts
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - echo localhost `cat /etc/ssh/ssh_host_ecdsa_key.pub` >> ~/.ssh/known_hosts
  - mkdir ~/x
  - mkdir ~/y
  - sshfs ~/x localhost:y
env:
  - GOMV_TEST_CROSS_VOLUME_UNIX_TARGET=~/x
  
